---

- name: Provisioning datalab
  hosts: 
    - datalab

  roles:
    - role: ansible-role-docker

    - role: ansible-role-centos-python
      pyfsrc_version: 3.5.2
      pyfsrc_make_default: yes
      pyfsrc_ssl_support: yes
      pyfsrc_install_pip: yes

    - role: ansible-role-centos-jupyterhub
      jupyterhub_spawner: 'dockerspawner'
      jupyterhub_spawner_docker_image: 'natbusa/sysuser-scipy-lab'
      generate_testusers: True
      gen_test_username:
        - amy
        - joe
        - sue
        - bob

  vars:
    docker_create_group: true
