---

- name: Provisioning datalab
  hosts: 
    - datalab

  roles:
    - role: ansible-role-docker
    - role: ansible-role-centos-python
      pyfsrc_version: 3.5.2
      pyfsrc_make_default: yes
      pyfsrc_ssl_support: yes
      pyfsrc_install_pip: yes

  vars:
    docker_create_group: true